/* Version information for Stats.
 *
 * (c) 2004-2011 Denora Team
 * Contact us at info@denorastats.org
 *
 * Please read COPYING and CREDITS for furhter details.
 *
 * Based on the original code of Anope by Anope Dev.
 * Based on the original code of Thales by Lucas.
 * 
 * This file is auto-generated by version.sh
 *
 * $Id: mod_version.c 386 2011-01-04 17:16:43Z hal9000 $
 *
 */

#include "denora.h"

E int getDenoraBuildVersion(void);
E int getDenoraMajorVersion(void);
E int getDenoraMinorVersion(void);
E int getDenoraPatchVersion(void);

int getDenoraBuildVersion(void)
{
    return VERSION_BUILD;
}

int getDenoraMajorVersion(void)
{
    return VERSION_MAJOR;
}

int getDenoraMinorVersion(void)
{
    return VERSION_MINOR;
}

int getDenoraPatchVersion(void)
{
    return VERSION_PATCH;
}
